# Generated by Django 3.0.5 on 2020-05-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20200502_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='signal_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='id'),
        ),
    ]
