# Generated by Django 3.0.5 on 2020-09-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_remove_group_member'),
        ('authentication', '0008_auto_20200823_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='group',
            field=models.ManyToManyField(to='content.Group', verbose_name='groups'),
        ),
    ]
