# Generated by Django 3.0.5 on 2020-09-01 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_auto_20200901_1825'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
