# Generated by Django 3.0.5 on 2020-09-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_userprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='comments_notifs',
            field=models.BooleanField(default=True, verbose_name='comments notifications'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='follow_post_notifs',
            field=models.BooleanField(default=True, verbose_name='follower post notifications'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='like_notifs',
            field=models.BooleanField(default=True, verbose_name='like notifications'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='new_follow_notifs',
            field=models.BooleanField(default=True, verbose_name='new follower notifications'),
            preserve_default=False,
        ),
    ]
