# Generated by Django 3.0.5 on 2020-08-29 10:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_post_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='pic',
            field=models.FileField(blank=True, null=True, upload_to='group', verbose_name='picture'),
        ),
    ]
