# Generated by Django 3.0.5 on 2020-08-29 13:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0007_auto_20200829_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='member',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='members'),
        ),
    ]
