# Generated by Django 3.0.5 on 2020-09-01 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_membership'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='group',
            new_name='joined_group',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='user',
            new_name='member',
        ),
    ]
