# Generated by Django 3.0.5 on 2020-09-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_auto_20200921_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='secret',
            field=models.IntegerField(default=7170895, editable=False, verbose_name='secret'),
        ),
    ]
