# Generated by Django 3.0.5 on 2020-09-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_group_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='secret',
            field=models.IntegerField(default=48052232110414, editable=False, verbose_name='secret'),
        ),
    ]
