# Generated by Django 3.0.5 on 2020-09-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_auto_20200922_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='secret',
            field=models.IntegerField(default=34567345, verbose_name='secret'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='secret',
            field=models.IntegerField(default=50750294069248, editable=False, verbose_name='secret'),
        ),
    ]
