# Generated by Django 3.0.5 on 2020-09-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_auto_20200922_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='secret',
            field=models.IntegerField(default=32642360902322, editable=False, verbose_name='secret'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='secret',
            field=models.IntegerField(blank=True, null=True, verbose_name='secret'),
        ),
    ]
