# Generated by Django 3.0.5 on 2020-09-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0022_auto_20200922_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='secret',
            field=models.IntegerField(default=41788921855184, editable=False, verbose_name='secret'),
        ),
    ]
