# Generated by Django 3.0.5 on 2020-09-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0023_auto_20200922_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='secret',
            field=models.IntegerField(default=1900347440, editable=False, verbose_name='secret'),
        ),
    ]
