# Generated by Django 3.0.5 on 2020-09-22 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0024_auto_20200922_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='secret',
            field=models.IntegerField(default=194426059, editable=False, verbose_name='secret'),
        ),
    ]
