# Generated by Django 3.0.5 on 2020-10-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0027_auto_20200928_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='secret',
            field=models.BigIntegerField(default=2041149950486188476, editable=False, verbose_name='secret'),
        ),
    ]
