# Generated by Django 3.0.5 on 2020-10-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0028_auto_20201008_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='secret',
            field=models.BigIntegerField(default=1455674064103186638, editable=False, verbose_name='secret'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='secret',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='secret'),
        ),
    ]
