# Generated by Django 3.0.5 on 2020-10-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0029_auto_20201009_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='secret',
            field=models.BigIntegerField(default=7890365713121601810, editable=False, verbose_name='secret'),
        ),
    ]
