# Generated by Django 3.0.5 on 2020-10-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0030_auto_20201009_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='secret',
            field=models.CharField(default=b'\xc8NJ\xe0\xfe\xdc\xf9\xc55\x02#\x04C>?_', editable=False, max_length=200, verbose_name='secret'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='secret',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='secret'),
        ),
    ]
